/**
 * Expanded, detailed answer texts for each interview question.
 * Imported by data.js and merged at runtime.
 */
export const expandedAnswers = {
    q1: "Hoisting is JavaScript's default behavior of moving variable and function declarations to the top of their containing scope (global or function) before any code executes. Critically, ONLY the declaration is hoisted — not the initialization. var declarations are hoisted and auto-initialized to undefined, so reading a var before its assignment line returns undefined instead of throwing an error. let and const are also hoisted but enter a Temporal Dead Zone (TDZ) — any access to them before their declaration line throws a ReferenceError. Function declarations are fully hoisted (both name and body), which is why you can call them anywhere in their scope. Function expressions, arrow functions, and class declarations follow variable-hoisting rules and are NOT usable before their definition line. Hoisting is per-scope: inside a function, declarations hoist to the top of that function only, not to the global scope.",

    q2: "A closure is a function that retains a live reference to variables from its outer (enclosing) lexical scope even after that outer function has returned and its execution context has been garbage-collected. Every function in JavaScript forms a closure at definition time — it captures its surrounding environment, not a snapshot. This means mutations to closed-over variables are visible inside the closure. Closures are the foundation of: private state (the counter pattern), the revealing module pattern (IIFE), memoization, debounce and throttle utilities, and React Hooks (useState, useEffect, and all hooks rely on closures to persist state across renders). The classic interview trap is the var-in-loop bug: var is function-scoped, so all loop iterations share the same binding — every callback closes over the same variable and sees its final value. The fix is to use let (block-scoped per iteration), an IIFE that captures the current iteration value, or Array.from with a mapping function.",

    q3: "== (loose equality) performs Abstract Equality Comparison — a complex multi-step algorithm in the ECMAScript specification that coerces operands to a common type before comparing. === (strict equality) checks type first: if the types differ it returns false immediately, no conversion is performed. The coercion rules of == are notoriously unintuitive: empty string equals false, empty array equals false, empty array equals the negation of empty array — these are real production bug sources. Always default to === in your code. There are exactly two idiomatic uses of ==: value == null cleanly catches both null and undefined in one expression, and it is the recommended check in the ECMAScript spec itself. Additionally, learn Object.is() for precision edge cases: Object.is(NaN, NaN) returns true (unlike ===), and Object.is(+0, -0) returns false (unlike === which treats them as equal).",

    q4: "JavaScript is single-threaded — it has one Call Stack and can only execute one piece of code at a time. The Event Loop is the runtime mechanism that enables non-blocking asynchronous behavior. When asynchronous work is initiated (fetch, setTimeout, DOM events, I/O), the JavaScript engine delegates it to the host environment (browser Web APIs or Node.js C++ bindings). When that work completes, its callback is placed in a queue. The Event Loop constantly monitors: when the Call Stack is empty, it first drains the entire Microtask Queue (all pending Promise .then/.catch/.finally callbacks, queueMicrotask callbacks, and async/await continuations), then picks exactly one task from the Macrotask Queue (setTimeout, setInterval, setImmediate, I/O). After that macrotask runs, microtasks are drained again before the next macrotask. This ordering is why Promise callbacks always execute before setTimeout callbacks, even with 0ms delay. A critical performance concern: if your code floods the microtask queue (e.g. recursive Promise.resolve), it will starve macrotasks and block rendering.",

    q5: "'this' is a dynamic binding in JavaScript that refers to the context object — the object that is the receiver of the current function call. Its value is resolved at call time using four binding rules in order of decreasing precedence: (1) new binding: when a function is called with new, 'this' refers to the freshly created object; (2) explicit binding: call(ctx), apply(ctx, args), and bind(ctx) forcibly set 'this' to ctx; (3) implicit binding: when a function is called as a method (obj.method()), 'this' refers to the object left of the dot; (4) default binding: a standalone function call resolves 'this' to the global object (window/globalThis) in sloppy mode, or undefined in strict mode. Arrow functions are the critical exception — they have NO own 'this' context. Instead, they permanently capture 'this' from their enclosing lexical scope at the time they are defined. This makes arrow functions ideal for callbacks, class methods that use setInterval, and anywhere you need to preserve the surrounding context.",

    q6: "Every JavaScript object has a hidden [[Prototype]] internal slot that links it to another object (or null). When you access a property on an object, the JavaScript engine first checks the object's own properties. If not found, it traverses up the prototype chain — checking the [[Prototype]] object, then its [[Prototype]], and so on until it either finds the property or reaches null (the end of the chain). This is called prototypal inheritance. All built-in objects (arrays, functions) have Object.prototype at the top of their chain, which provides universal methods like toString(), hasOwnProperty(), and valueOf(). ES6 class and extends are 100% syntactic sugar built directly on top of this prototype mechanism — they do NOT introduce classical inheritance. Understanding the chain is essential for: debugging inherited properties, understanding instanceof checks (which traverses the chain), knowing what for...in iterates (all enumerable properties up the chain), and writing efficient code (long chains slow down property lookups).",

    q7: "Destructuring, spread, and rest are three related ES6+ syntactic features that make working with arrays and objects far more concise. Destructuring lets you extract values into named variables — you can set defaults, rename variables, skip elements, and destructure deeply nested structures. Object destructuring is especially useful in React for extracting props. Spread syntax (...) expands an iterable or object into its individual elements — it is the standard way to do shallow copies and merge arrays/objects in modern JavaScript. A critical detail: for objects, later spread keys overwrite earlier ones, making it useful for applying overrides to a base config. Rest syntax (...) collects remaining elements (when destructuring) or arguments (in function parameters) into a single array, enabling clean variadic functions. All three syntaxes are heavily used in React (destructuring props and state, spreading component props, rest props in component wrappers).",

    q8: "A Promise is an object representing the eventual result (or failure) of an asynchronous operation. It can be in one of three states: pending, fulfilled (resolved with a value), or rejected (with a reason). Promises are the foundation of async JavaScript — they replace nested callbacks with chainable .then()/.catch()/.finally() methods, making async code linear and readable. There are four powerful static combinator methods: Promise.all() takes an array of promises and resolves when ALL fulfill, but rejects immediately if ANY one rejects (fail-fast); Promise.allSettled() waits for ALL promises to settle and returns an array of {status, value/reason} objects — it NEVER rejects; Promise.race() resolves or rejects as soon as the FIRST promise settles; Promise.any() resolves with the FIRST fulfilled value and only rejects if ALL promises reject (AggregateError). Choosing the right combinator is a key interview topic: use all() for dependent parallel operations, allSettled() for independent parallel fetches where you need every result.",

    q9: "async/await is syntactic sugar over Promises that allows you to write asynchronous code in a synchronous-looking style. An async function always returns a Promise implicitly — if you return a non-Promise value, it is automatically wrapped. The await keyword pauses the execution of the async function until the Promise settles, then resumes with the resolved value. If the Promise rejects, await throws the rejection reason, which you can catch with try/catch. Critical performance pattern: if you use await sequentially on independent async operations (await A; then await B), you serialize them — they run one after another. To run them in parallel, always use Promise.all([A, B]) with a single await. This can reduce latency from the sum of all durations to just the longest one. Always add try/catch/finally for error handling — unhandled promise rejections crash Node.js processes and cause silent failures in browsers.",

    q10: "The Virtual DOM (VDOM) is a lightweight JavaScript object tree that represents the structure of the actual browser DOM. It is cheap to create and manipulate compared to real DOM operations, which trigger layout recalculations and paint cycles. When component state changes, React creates a NEW VDOM tree and diffs it against the previous one using its reconciliation algorithm (now powered by React Fiber). The differ detects the minimum set of changes needed and batches them into a single efficient real DOM update. React Fiber (introduced in React 16) replaced the old stack-based reconciler with a linked-list architecture that enables incremental, prioritized, and interruptible rendering. React 18 extended this with concurrent features: startTransition marks updates as non-urgent, useTransition enables rendering UIs that don't block on slow state updates, and useDeferredValue defers non-critical renders. Keys are critical for list reconciliation — they tell React which list items identity persists across renders, preventing it from destroying and recreating unnecessarily.",

    q11: "Controlled components are form elements (inputs, selects, textareas) whose value is driven entirely by React state — the component's state is the single source of truth. Every keypress updates state via an onChange handler, which re-renders the input with the new value. This gives you full control for real-time validation, conditional disabling, and derived computations. Uncontrolled components let the DOM (not React) manage form state internally. You access the current value imperatively via a ref (inputRef.current.value) — typically only on form submit. This is simpler for basic forms and required for file inputs (which cannot be controlled). React Hook Form is a popular third-party library that blurs the line — it uses uncontrolled inputs internally for performance but provides a controller-based API for validation. The rule of thumb: use controlled components when you need to respond to every change (live validation, conditional fields); use uncontrolled for performance-sensitive large forms or integration with non-React DOM libraries.",

    q12: "useState is the fundamental React hook for local component state. It returns a tuple: the current state value and a setter function. The setter can accept either a new value directly or a functional updater — a function that receives the previous state and returns the next. Always prefer the functional updater form when the new state depends on the old state, because React may batch or delay state updates, making the directly-captured state value stale inside closures (callbacks, timers). useState supports lazy initialization: if initial computation is expensive, pass a function instead of a value — it is called only once on mount. For object state, always spread the previous state when updating a subset of fields (setUser(prev => ({ ...prev, name: 'Bob' }))) because useState replaces state entirely unlike class setState which merges. In React 18+, all state updates are automatically batched — multiple setState calls in a single event handler or async callback cause only one re-render.",

    q13: "useEffect synchronizes a component to external systems (data fetching, subscriptions, timers, manual DOM manipulation). It runs AFTER the component renders and paints to the screen. The dependency array controls when the effect re-runs: no array means every render, empty array means mount only, and a list of values means when any of them change. The return value is a cleanup function — it runs before the component unmounts AND before the effect re-runs when dependencies change. Always clean up subscriptions, timers, and abort controllers to prevent memory leaks. A critical async pattern: never make the effect callback itself async (useEffect(() => async function is anti-pattern) — define an async function inside and call it, and use an isCancelled flag or AbortController to guard stale state updates when the component unmounts between fetch and response. useLayoutEffect is a synchronous variant that runs before the browser paints — use it exclusively for measuring DOM dimensions or preventing visual flicker. As of React 18 in Strict Mode, effects run twice in development to help detect side-effect bugs.",

    q14: "useMemo caches the result of an expensive computation between renders. It recomputes only when one of its listed dependencies changes. useCallback is useMemo specialized for functions — it caches a function reference, returning the same reference across renders unless dependencies change. Both hooks exist to solve referential equality issues in React: because a new object or function is created on every render, a child component wrapped in React.memo would re-render even if the logically-equivalent data didn't change. The critical caveat: these hooks only help if the child receiving the value/function is wrapped in React.memo. Without that, the child always re-renders regardless of reference stability. Do NOT use these hooks prematurely — they add overhead (the comparison itself has a cost) and make the code harder to read. Profile your app first with React DevTools Profiler, then add useMemo/useCallback only where measurements show a genuine render performance problem. The React Compiler (formerly React Forget) automates this optimization.",

    q15: "useRef returns a mutable container object { current: initialValue } that persists for the full lifetime of the component. Unlike state, mutating ref.current does NOT trigger a re-render — it is invisible to React's rendering system. This makes refs perfect for: (1) accessing DOM elements imperatively (focus, scroll, measure dimensions with getBoundingClientRect); (2) storing mutable values that must persist across renders but shouldn't trigger re-renders (timer IDs, previous values, accumulator counters); (3) the 'previous value' pattern — because the ref update in useEffect runs after render, ref.current holds the previous render's value when read inside JSX. Refs are also forwarded to child components using React.forwardRef, which is required for any component that needs to expose a DOM node or imperative handle to its parent. useImperativeHandle (paired with forwardRef) lets you customize which methods are exposed through the ref rather than exposing the full DOM node.",

    q16: "useContext provides a way to share values across the component tree without manually passing props through every intermediate component (prop drilling). You create a context with createContext(defaultValue), wrap a subtree in the context Provider, and any descendant can read the current value with useContext(MyContext). Critically: every component that calls useContext re-renders whenever the context value changes — so avoid putting frequently-changing state (mouse position, scroll) in a top-level context. Split large contexts into multiple smaller ones to minimize unnecessary re-renders. useReducer is React's built-in state manager for complex state: it takes a pure reducer function and an initial state, and returns the current state plus a dispatch function. Unlike useState, state transitions are explicit and named (dispatched actions), making them easier to test, debug with Redux DevTools, and audit in code review. The idiomatic pattern for app-wide state is combining useContext + useReducer: the context provides a dispatch function and state, the reducer enforces all state transitions.",

    q17: "Custom hooks are functions whose names start with 'use' and that call other React hooks internally. They let you extract stateful logic out of components and share it across multiple components without changing the component tree structure (no HOC wrapper, no render prop). The 'use' prefix is not just a convention — it tells React's linter and tooling that the function must follow the rules of hooks (only called at top level, only inside React functions). Custom hooks can encapsulate anything: data fetching (useFetch), form state management, WebSocket connections (useWebSocket), localStorage sync (useLocalStorage), keyboard shortcuts, intersection observers, media queries, and more. They return whatever the consumer needs — typically an object or array. Libraries like react-query, SWR, and Zustand expose their functionality primarily through custom hooks. When you find yourself copying stateful logic between two or more components, that is the signal to extract a custom hook.",

    q18: "React.memo is a higher-order component that prevents a functional component from re-rendering if its props are shallowly equal to the previous render's props. It is the functional equivalent of shouldComponentUpdate/PureComponent for class components. Important: 'shallowly equal' means object/array/function references are compared with ===. If a parent re-renders and creates a new object or function literal on every render, memo won't help unless the references are stabilized with useMemo/useCallback. Code splitting with React.lazy() and Suspense loads component bundles on demand — reducing the initial JavaScript bundle size and improving time-to-interactive. Strategic splitting points: route-level components (each page is a separate chunk), heavy modal/drawer content, data visualization libraries, and rich text editors. List virtualization (react-window, react-virtual) solves the performance problem of rendering large lists — instead of rendering 10,000 DOM nodes, it renders only the visible items (typically 10-20) and recycles them as the user scrolls.",

    q19: "Next.js provides four rendering strategies in the App Router, each controlled by the fetch() cache option. SSG (Static Site Generation) is the default: pages are rendered at build time, result cached as static HTML, and served instantly from a CDN — ideal for blogs, documentation, and marketing pages where data rarely changes. ISR (Incremental Static Regeneration) adds revalidation to SSG: static pages are served immediately but revalidated in the background at specified intervals (next: { revalidate: 60 } means check for new data every 60 seconds). ISR gives you static performance with up-to-date data — ideal for product pages, news sites. SSR (Server-Side Rendering) generates fresh HTML on every request (cache: 'no-store') — necessary for pages with user-specific content, real-time data, or cookie-dependent rendering. CSR (Client-Side Rendering) uses a loading skeleton on the server and fetches data from the client — traditional React SPA behavior, appropriate for auth-gated dashboards. Choosing the right strategy dramatically affects SEO, TTFB, and infrastructure cost.",

    q20: "Next.js App Router uses the file system as the routing configuration. Folders define URL segments and special filenames create specific behavior: page.tsx makes a route publicly accessible, layout.tsx wraps child segments in a persistent shell that doesn't re-mount on navigation (ideal for sidebars, headers), loading.tsx automatically creates a Suspense boundary with a fallback shown while the page segment loads, error.tsx creates an error boundary that catches render errors and shows a recovery UI, and not-found.tsx renders the 404 experience. Route Groups — directories wrapped in parentheses like (marketing) — let you share layouts across routes without affecting the URL structure, perfect for grouping authenticated routes or applying different layouts to different sections. Dynamic segments ([slug], [...slug], [[...slug]]) handle variable URL parts. Parallel routes (@slot) allow rendering multiple pages simultaneously in the same layout, enabling complex UIs like dashboards with independent sections.",

    q21: "Server Components (RSC) are the default in the Next.js App Router. They render exclusively on the server — their output is a serialized React tree sent to the client, with ZERO JavaScript shipped to the browser for the component itself. This means: smaller bundles, faster hydration, and direct access to server resources (databases, file systems, environment secrets) without needing API routes. Server Components can be async — you can await database queries directly in the component body. Client Components are marked with the 'use client' directive at the top of the file. They run on both the server (for initial HTML) and the client (for interactivity). You need Client Components for: React hooks (useState, useEffect), browser APIs (localStorage, window), event handlers, and third-party libraries that use these. The composition rule: a Server Component CAN render a Client Component (passing it serializable props). But a Client Component CANNOT import a Server Component directly — though it can accept one as children or a prop (the server renders it before passing).",

    q22: "Server Actions are async functions that run exclusively on the server but can be called directly from Client Components — without writing a separate API route. They are declared with the 'use server' directive (either at the top of a file to make all exports server actions, or within an async function). When called from a form's action attribute, they provide progressive enhancement: the form works without JavaScript (native HTML form submission) and upgrades to a smooth mutation when JS is loaded. After a mutation, use revalidatePath() or revalidateTag() to invalidate the Next.js Data Cache and trigger fresh data for affected routes. For client-side loading and error state, use the useActionState hook (React 19 / Next.js 15): it wraps the server action and returns [state, formAction, isPending] — isPending is true while the server is processing, enabling disabled buttons and loading spinners. Server Actions solve the full-stack mutation problem elegantly while maintaining type safety end-to-end.",

    q23: "Next.js has four distinct caching layers stacked on top of each other. Request Memoization deduplicates identical fetch() calls within the same render tree pass — if two Server Components both fetch the same URL with the same options in one render, only one HTTP request is made. The Data Cache persists fetch() results on disk across requests and deployments — this is where revalidate and cache options operate. The Full Route Cache stores the rendered RSC payload and HTML for statically generated routes — serving them without any server-side computation. The Router Cache is a client-side in-memory cache of RSC payloads — it enables instant navigation between previously visited routes. Understanding how these layers interact is critical: a Server Action that calls revalidatePath('/products') clears the Full Route Cache for that route AND all Data Cache entries for fetches tagged with that path. Use revalidateTag() for more surgical cache invalidation — tag related fetches and invalidate them as a group when mutations occur.",

    q24: "Higher-Order Components (HOCs), Render Props, and Custom Hooks are three patterns for sharing stateful logic between React components. HOCs are functions that take a component and return a new enhanced component — they work but suffer from: wrapper hell (deeply nested component trees), prop naming collisions, and difficulty tracing data flow. Render Props share logic via a prop that is a function — the component calls it with the shared data, and the consumer decides how to render. More explicit than HOCs but verbose and add JSX nesting. Custom Hooks (the modern, recommended approach) extract stateful logic into plain functions that start with 'use'. They are the cleanest pattern: no wrapper components, no nesting, no naming collisions, and fully composable. They work seamlessly with React DevTools and are the idiomatic solution in all modern React codebases. The React team explicitly recommends migrating HOC and render prop patterns to custom hooks when possible.",

    q25: "TypeScript with React and Next.js follows several key patterns. Prefer interface over type alias for component props — interfaces are extensible via declaration merging and generally provide better error messages. Generics make components genuinely reusable across multiple data types without duplicating code. Extend built-in HTML attribute interfaces (React.ButtonHTMLAttributes<HTMLButtonElement>) so custom components preserve all native attributes without manual re-typing. Discriminated unions (a union where each member has a unique literal type field) enable type-safe component variants — TypeScript narrows the type in a switch or if based on the discriminant. Utility types like Partial<T>, Required<T>, Pick<T, K>, Omit<T, K>, and Record<K, V> let you derive new types from existing ones without duplication. Next.js provides its own utility types (NextPage, PageProps, Metadata) that you should use rather than manually typing page exports — they stay in sync with the framework version.",

    q26: "JavaScript has three distinct notions of 'nothing': undefined means a variable has been declared but not yet assigned a value — variables are automatically undefined after declaration, missing object properties return undefined, and functions without a return statement return undefined. null is an intentional absence of value — a programmer explicitly sets something to null to indicate 'empty' or 'no object'. The famous quirk: typeof null === 'object' (a historical bug in the language specification that cannot be fixed for backwards compatibility). 'Undeclared' means the variable was never declared in any scope — accessing it throws a ReferenceError, but typeof of an undeclared variable safely returns the string 'undefined'. In practice: use value == null (loose equality) to catch both null and undefined, use === null or === undefined for precise type-specific checks, and understand that optional chaining (?.) and nullish coalescing (??) treat both null and undefined as 'nullish'.",

    q27: "This question tests mastery of the JavaScript Event Loop execution order. The output order is determined by three priority tiers: synchronous code runs first and completely (clearing the call stack), then the entire microtask queue drains (all Promise .then callbacks, queueMicrotask calls, and async/await continuations execute to completion), and only then does one macrotask (setTimeout callback) execute. After that macrotask, microtasks drain again before the next macrotask. This pattern repeats indefinitely. The async/await version of the question adds complexity: 'await' converts everything after it into a microtask continuation, so 'a1 end' (which is after an await) runs as a microtask, before 'timeout' (which is a macrotask). This knowledge is crucial for understanding React's rendering pipeline, why setState updates appear asynchronous, and why requestAnimationFrame timing works as it does.",

    q28: "Shallow copy and deep copy differ in how they handle nested reference types. A shallow copy creates a new top-level object, but nested objects and arrays are NOT copied — both the original and the copy point to the same nested references. Mutations to nested structures affect BOTH objects. Shallow copy methods: spread operator {...obj}, Object.assign({}, obj), Array.from(arr), and arr.slice() — all create shallow copies only. A deep copy creates a completely independent replica — every nested level is recursively copied. Methods: JSON.parse(JSON.stringify(obj)) is the quick-and-dirty solution but loses functions, undefined, Symbol, Date objects (converted to strings), Set, Map, and circular references (throws an error). structuredClone() is the modern native API (available in Node 17+ and all modern browsers) — it handles circular references, Date, Set, Map, ArrayBuffer, and more, but cannot clone functions or DOM nodes. For complex or custom class instances, use Lodash's cloneDeep().",

    q29: "Prop drilling is the anti-pattern of passing props through multiple intermediate components that don't use them — they only pass the data along to deeper children. This creates tight coupling between components and makes refactoring painful: changing the prop signature requires updating every intermediary. Solutions in order of complexity: (1) Component Composition — redesign the component tree to pass JSX elements as props instead of raw data, eliminating the need for intermediaries to know about the data at all; (2) React Context API — ideal for truly global data like theme, authenticated user, or locale — any component can consume it directly with useContext; (3) Zustand or Jotai — lightweight external state managers that store state outside React's component tree, making any piece of state accessible anywhere with a single hook call, without the performance pitfalls of Context for high-frequency updates; (4) Redux Toolkit — for large applications with complex state shape, many interacting slices, and need for DevTools, middleware, and time-travel debugging. Avoid over-engineering: start with composition, reach for Context, then evaluate external libraries.",

    q30: "WeakMap and WeakSet are special collection types that hold weak references to their keys (WeakMap) or members (WeakSet). 'Weak reference' means that if the key object has no other references pointing to it in normal code, the JavaScript garbage collector is free to reclaim it — and when it does, the WeakMap/WeakSet entry is automatically removed. This has two important consequences: they prevent memory leaks in long-running applications (no need to manually clean up), and they are NOT enumerable (you cannot iterate over them with for...of or get their size). Keys must be objects (not primitives like strings or numbers). Common use cases: per-element result caching without leaking memory when elements are removed from the DOM, implementing truly private instance data in classes (store sensitive data keyed on the instance), tracking processed objects without blocking GC, and polyfilling private class fields. WeakRef (ES2021) gives you explicit weak references with a .deref() method, and FinalizationRegistry lets you run callbacks when objects are garbage collected.",
};
